language: csharp
sudo: required
dist: trusty
env:
  matrix:
  - MODE=main
install:
    # Install runtime
  - |-
    sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
    sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
    sudo apt-get update
    sudo apt-get install dotnet-dev-1.0.0-rc4-004769 -y
script:
  - dotnet clean openapi-diff/OpenApiDiff.sln
  - dotnet restore openapi-diff/OpenApiDiff.sln
  - dotnet build -c debug openapi-diff/OpenApiDiff.sln /nologo /clp:NoSummary
  - dotnet test ./openapi-diff/src/modeler/AutoRest.Swagger.Tests/AutoRest.Swagger.Tests.csproj
