trigger:
- main

variables:
  Codeql.Enabled: true

strategy:
  matrix:
    Linux:
      Pool: azsdk-pool-mms-ubuntu-2204-general
      OsVmImage: ubuntu-22.04
      TargetFolder: drop-linux
    Windows:
      Pool: azsdk-pool-mms-win-2022-general
      OsVmImage: windows-2022
      TargetFolder: drop

pool:
  name: $(Pool)
  vmImage: $(OSVmImage)

steps:
- script: npm install
  displayName: npm install
- script: npm test
  displayName: test
- script: npm pack
  displayName: pack
- task: CopyFiles@2
  displayName: 'Copy Files to: $(TargetFolder)'
  inputs:
    Contents: '*.tgz'
    TargetFolder: $(TargetFolder)
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.SourcesDirectory)/$(TargetFolder)
    artifactName: $(TargetFolder)

- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2 # CredScan@2
  inputs:
    toolMajorVersion: 'V2'
  condition: and(succeeded(), eq(variables['Agent.OS'],'Windows_NT')) # CredScan only supported on Windows

- task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1 # PostAnalysis@1
  inputs:
    AllTools: false
    APIScan: false
    BinSkim: false
    CodesignValidation: false
    CredScan: true
    FortifySCA: false
    FxCop: false
    ModernCop: false
    PoliCheck: false
    RoslynAnalyzers: false
    SDLNativeRules: false
    Semmle: false
    TSLint: false
    ToolLogsNotFoundAction: 'Standard'
  condition: and(succeeded(), eq(variables['Agent.OS'],'Windows_NT')) # CredScan only supported on Windows
