trigger:
- main

resources:
  repositories:
  - repository: azure-sdk-tools
    type: github
    name: Azure/azure-sdk-tools    
    endpoint: Azure
    ref: refs/tags/azure-sdk-tools_20250709.1

extends:
  template: /eng/1es-redirect.yml
  parameters:
    stages:
    - stage: Build_And_Test
      variables:
        - template: /eng/image.yml
      jobs:
        - job: Build_linux

          pool:
            name: $(LINUXPOOL)
            image: $(LINUXVMIMAGE)
            os: linux

          steps:
            - template: /eng/test-steps.yml
              parameters:
                ArtifactName: drop-linux

        - job: Build_Windows

          pool:
            name: $(WINDOWSPOOL)
            image: $(WINDOWSVMIMAGE)
            os: windows

          steps:
            - template: /eng/test-steps.yml
              parameters:
                ArtifactName: drop


    # only include if running on `internal` build with manual queue, otherwise never include
    - ${{ if and(in(variables['Build.Reason'], 'Manual', ''), eq(variables['System.TeamProject'], 'internal'))}}:
      - stage: Publish
        dependsOn: Build_And_Test
        jobs:
        - template: /eng/common/pipelines/templates/jobs/npm-publish.yml@azure-sdk-tools
          parameters:
            ArtifactName: drop-linux
