trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: npm install
  displayName: npm install
- script: npm test
  displayName: test
- script: npm pack
  displayName: pack
- task: CopyFiles@2
  displayName: 'Copy Files to: drop'
  inputs:
    Contents: '*.tgz'
    TargetFolder: drop
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.SourcesDirectory)/drop
