trigger:
- main

variables:
  Codeql.Enabled: true

pool:
  name: azsdk-pool-mms-win-2022-general
  vmImage: windows-2022

steps:
- script: npm install
  displayName: npm install
- script: npm test
  displayName: test
- script: npm pack
  displayName: pack
- task: CopyFiles@2
  displayName: 'Copy Files to: drop'
  inputs:
    Contents: '*.tgz'
    TargetFolder: drop
- task: PublishBuildArtifacts@1
  inputs:
    pathtoPublish: $(Build.SourcesDirectory)/drop

- task: securedevelopmentteam.vss-secure-development-tools.build-task-credscan.CredScan@2 # CredScan@2
  inputs:
    toolMajorVersion: 'V2'

- task: securedevelopmentteam.vss-secure-development-tools.build-task-postanalysis.PostAnalysis@1 # PostAnalysis@1
  inputs:
    AllTools: false
    APIScan: false
    BinSkim: false
    CodesignValidation: false
    CredScan: true
    FortifySCA: false
    FxCop: false
    ModernCop: false
    PoliCheck: false
    RoslynAnalyzers: false
    SDLNativeRules: false
    Semmle: false
    TSLint: false
    ToolLogsNotFoundAction: 'Standard'


