swagger: '2.0'
info:
  version: 1.0.0
  title: PetStore on Heroku
  description: |
    **This example has a working backend hosted in Heroku**

    You can try all HTTP operation described in this Swagger spec.
    
    Find source code of this API [here](https://github.com/mohsen1/petstore-api)
host: petstore-api.herokuapp.com
basePath: /pet
schemes:
  - http
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/html
paths:
  /:
    get:
      operationId: get_pets
      parameters:
        - name: limit
          in: query
          description: number of pets to return
          type: integer
          default: 11
          minimum: 11
          maximum: 10000
      responses:
        200:
          description:  List all pets
          schema:
            title: Pets
            type: array
            items:
              $ref: '#/definitions/Pet'
    post:
      operationId: post_pets
      parameters:
        - name: pet
          in: body
          description: The pet JSON you want to post
          schema:
            $ref: '#/definitions/Pet'
          required: true
      responses:
        200:
          description: Make a new pet
    put:
      operationId: put_pets
      parameters:
        - name: pet
          in: body
          description: The pet JSON you want to post
          schema:
            $ref: '#/definitions/Pet'
          required: true
      responses:
        200:
          description: Updates the pet

definitions:
  Pet:
    type: object
    additionalProperties: 
      type: object
      $ref: '#/definitions/Feature'
      
    properties:
      name:
        type: string
      birthday:
        type: integer
        format: int32
      wsd:
        type: object
        $ref: '#/definitions/WithStringDictionary'
      wud: 
        type: object
        $ref: '#/definitions/WithUntypedDictionary'
      wtd: 
        type: object
        $ref: '#/definitions/WithTypedDictionary'

  Feature:
    type: object
    properties:
      foo:
        type: string
      bar: 
        type: integer
        format: int32
      
  WithStringDictionary:
    type: object
    properties: 
      abc:
        type: string
    additionalProperties: 
      type: string
    
  WithUntypedDictionary:
    properties: 
      abc:
        type: string
    type: object
    additionalProperties: 
      type: object

  WithTypedDictionary:
    type: object
    properties: 
      abc:
        type: string
    additionalProperties: 
      type: object
      $ref: '#/definitions/Feature'
