name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: "22"

      - uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6.0.0
        with:
          dotnet-version: "6"

      - name: npm ci
        run: npm ci

      - name: test
        run: npm test

      - name: lint
        run: npm run lint

      - name: prettier
        run: npm run prettier

      - if: runner.os == 'Linux'
        name: Pack
        run: npm pack

      - if: runner.os == 'Linux'
        name: Upload tarball
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          path: "azure-oad-*.tgz"
          archive: false

      # Content copied from https://raw.githubusercontent.com/rhysd/actionlint/2ab3a12c7848f6c15faca9a92612ef4261d0e370/.github/actionlint-matcher.json
      - if: runner.os == 'Linux'
        name: Add ActionLint Problem Matcher
        run: echo "::add-matcher::.github/matchers/actionlint.json"

      - if: runner.os == 'Linux'
        name: Lint workflows
        uses: docker://rhysd/actionlint:1.7.11
        with:
          args: -color -verbose
